# Generated by Django 6.0.2 on 2026-02-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('file_path', models.CharField(help_text='Relative path to the .md file in notes/docs/', max_length=500)),
                ('source', models.CharField(blank=True, help_text='Original filename (for imported files)', max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Your notes about this document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
